### ISSUE TITLE
How Can I Find The Vulnerabilities Found?

### ISSUE THREAD

**Issue by ChayimFriedman2** [snyk/vulncost#13]

**Comment by thisislawatts** [comment]
Hey @ChayimFriedman2, you can find more detailed information about the vulnerabilities by clicking through to Learn about this vulnerabilities.

Does that answer your question?

![screenshot 2020-04-10 at 13 26 44](https://user-images.githubusercontent.com/472589/78987670-f6f22d80-7b2e-11ea-83a7-6acbe99f6fe4.png)

**Comment by ChayimFriedman2** [comment]
Yes, thank you.
