### ISSUE TITLE
Package scanning non packages

### ISSUE THREAD

**Issue by remy** [snyk/vulncost#29]
See screenshot

<img width="639" alt="Screenshot 2020-04-29 at 09 23 46" src="https://user-images.githubusercontent.com/13700/80576008-56d84780-89fc-11ea-8587-d169542cabed.png">

Not even sure how it picked up this line to scan…(sorry I couldn't be more help at this point).

My package at that point in time: https://github.com/snyk/os-portal/blob/3657ded9d90b0c87d89bd46c0d4215851a456e05/package.json

**Comment by bmvermeer** [comment]
Thanks @remy, I will take a look because this looks weird indeed.
