### ISSUE TITLE
Indicate that no vulnerabilities were found on the imported module 

### ISSUE THREAD

**Issue by pkey** [snyk/vulncost#8]
**Why**

At the moment, when the scan is finished and no vulnerabilities are found, there is no indicator to tell that. It leaves the user guessing.

**What**

Have an indicator (for intance, a checkmark) which would be shown briefly after successful scan is done.

**Comment by bmvermeer** [comment]
implemented in version 1.1.0

**Comment by pkey** [comment]
🚀
